import { Sphere, Vector3 } from "@og-three";
import {
  bootstrapExample,
  mountControls,
  replaceSceneObject,
} from "../shared/runtime";

bootstrapExample({
  title: "Shape: Sphere",
  description: "Interactive UV-sphere primitive generated by the kernel.",
  build: ({ scene }) => {
    let current: Sphere | null = null;

    mountControls(
      "Sphere Parameters",
      [
        { type: "number", key: "radius", label: "Radius", min: 0.2, max: 3, step: 0.05, value: 1.0 },
        { type: "number", key: "widthSegments", label: "Width Segments", min: 3, max: 96, step: 1, value: 32 },
        { type: "number", key: "heightSegments", label: "Height Segments", min: 2, max: 64, step: 1, value: 20 },
        { type: "boolean", key: "outline", label: "Outline", value: true },
      ],
      (state) => {
        const radius = state.radius as number;
        const sphere = new Sphere({
          center: new Vector3(0, radius, 0),
          radius,
          widthSegments: Math.floor(state.widthSegments as number),
          heightSegments: Math.floor(state.heightSegments as number),
          color: 0x0891b2,
        });
        sphere.outline = state.outline as boolean;

        current = replaceSceneObject(scene, current, sphere);
      }
    );
  },
});
