import { mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "vite";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const examplesRoot = resolve(__dirname, "examples-vite");
const examplesSourceRoot = resolve(examplesRoot, "src/examples");

function collectFiles(dir, extension, files = []) {
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stats = statSync(fullPath);
    if (stats.isDirectory()) {
      collectFiles(fullPath, extension, files);
      continue;
    }

    if (extname(fullPath) === extension) {
      files.push(fullPath);
    }
  }

  return files;
}

function toPosixPath(path) {
  return path.replace(/\\/g, "/");
}

function createExampleHtml(slug) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OpenGeometry Example</title>
  </head>
  <body data-example-slug="${slug}">
    <!-- Generated by vite.examples.config.mjs. Do not edit directly. -->
    <div id="app"></div>
    <script type="module" src="../src/example-page.ts"></script>
  </body>
</html>
`;
}

function syncGeneratedExampleEntries() {
  const moduleFiles = collectFiles(examplesSourceRoot, ".ts");

  const inputs = {
    index: resolve(examplesRoot, "index.html"),
  };

  for (const modulePath of moduleFiles) {
    const slug = toPosixPath(relative(examplesSourceRoot, modulePath)).replace(/\.ts$/, "");
    const htmlPath = resolve(examplesRoot, `${slug}.html`);
    mkdirSync(dirname(htmlPath), { recursive: true });
    writeFileSync(htmlPath, createExampleHtml(slug));
    inputs[slug] = htmlPath;
  }

  return inputs;
}

const input = syncGeneratedExampleEntries();

export default defineConfig({
  root: examplesRoot,
  base: "./",
  build: {
    outDir: resolve(__dirname, "examples-dist"),
    emptyOutDir: true,
    rollupOptions: { input },
  },
  resolve: {
    alias: {
      "@og-three": resolve(__dirname, "index.ts"),
    },
  },
  server: {
    fs: {
      allow: [resolve(__dirname, ".."), __dirname],
    },
  },
});
