// main/opengeometry-three/src/registry/layers.ts
// Auto-generated from aia-layers.yaml

export enum AIALayer {
  A_ANNO = 'A-ANNO',
  A_CALO = 'A-CALO',
  A_CASE = 'A-CASE',
  A_CEIL = 'A-CEIL',
  A_COLS = 'A-COLS',
  A_DEMO = 'A-DEMO',
  A_DIMN = 'A-DIMN',
  A_DOOR = 'A-DOOR',
  A_ELEM = 'A-ELEM',
  A_ELEV = 'A-ELEV',
  A_EQPM = 'A-EQPM',
  A_ESCL = 'A-ESCL',
  A_EXST = 'A-EXST',
  A_FLOR = 'A-FLOR',
  A_FLOR_RAIL = 'A-FLOR-RAIL',
  A_FLOR_RAMP = 'A-FLOR-RAMP',
  A_FLOR_STRS = 'A-FLOR-STRS',
  A_FURN = 'A-FURN',
  A_FUTR = 'A-FUTR',
  A_GLAZ = 'A-GLAZ',
  A_GLAZ_CW = 'A-GLAZ-CW',
  A_GLAZ_SF = 'A-GLAZ-SF',
  A_GRID = 'A-GRID',
  A_OPEN = 'A-OPEN',
  A_PLMB = 'A-PLMB',
  A_ROOF = 'A-ROOF',
  A_SECM = 'A-SECM',
  A_SHAF = 'A-SHAF',
  A_TEMP = 'A-TEMP',
  A_WALL = 'A-WALL',
  E_COND = 'E-COND',
  E_CTRAY = 'E-CTRAY',
  E_LITE = 'E-LITE',
  F_SPRK = 'F-SPRK',
  G_CURB = 'G-CURB',
  G_DRAN = 'G-DRAN',
  G_FENC = 'G-FENC',
  G_LNDS = 'G-LNDS',
  G_PARK = 'G-PARK',
  G_RETW = 'G-RETW',
  G_ROAD = 'G-ROAD',
  G_SITE = 'G-SITE',
  G_SWAL = 'G-SWAL',
  GENERAL = 'GENERAL',
  HIDDEN = 'HIDDEN',
  M_DUCT = 'M-DUCT',
  P_PIPE = 'P-PIPE',
  REFERENCE = 'REFERENCE',
  S_BEAM = 'S-BEAM',
  S_BRAC = 'S-BRAC',
  S_COLN = 'S-COLN',
  S_DECK = 'S-DECK',
  S_FOOT = 'S-FOOT',
  S_GIRD = 'S-GIRD',
  S_GRDN = 'S-GRDN',
  S_JOIS = 'S-JOIS',
  S_MOMF = 'S-MOMF',
  S_SHWR = 'S-SHWR',
  S_TRUS = 'S-TRUS',
  T_SEC = 'T-SEC',
  T_TELC = 'T-TELC',
}

export const ENTITY_TO_LAYER: Record<string, AIALayer> = {
  'wall': AIALayer.A_WALL,
  'walls': AIALayer.A_WALL,
  'partition': AIALayer.A_WALL,
  'door': AIALayer.A_DOOR,
  'doors': AIALayer.A_DOOR,
  'window': AIALayer.A_GLAZ,
  'windows': AIALayer.A_GLAZ,
  'glazing': AIALayer.A_GLAZ,
  'glaz': AIALayer.A_GLAZ,
  'glass': AIALayer.A_GLAZ,
  'curtainwall': AIALayer.A_GLAZ_CW,
  'curtain_wall': AIALayer.A_GLAZ_CW,
  'storefront': AIALayer.A_GLAZ_SF,
  'floor': AIALayer.A_FLOR,
  'floors': AIALayer.A_FLOR,
  'slab': AIALayer.A_FLOR,
  'slabs': AIALayer.A_FLOR,
  'floor_slab': AIALayer.A_FLOR,
  'roof': AIALayer.A_ROOF,
  'roofs': AIALayer.A_ROOF,
  'ceiling': AIALayer.A_CEIL,
  'ceilings': AIALayer.A_CEIL,
  'stair': AIALayer.A_FLOR_STRS,
  'stairs': AIALayer.A_FLOR_STRS,
  'staircase': AIALayer.A_FLOR_STRS,
  'stairwell': AIALayer.A_FLOR_STRS,
  'railing': AIALayer.A_FLOR_RAIL,
  'railings': AIALayer.A_FLOR_RAIL,
  'handrail': AIALayer.A_FLOR_RAIL,
  'guardrail': AIALayer.A_FLOR_RAIL,
  'ramp': AIALayer.A_FLOR_RAMP,
  'ramps': AIALayer.A_FLOR_RAMP,
  'column': AIALayer.A_COLS,
  'columns': AIALayer.A_COLS,
  'col': AIALayer.A_COLS,
  'pillar': AIALayer.A_COLS,
  'casework': AIALayer.A_CASE,
  'cabinet': AIALayer.A_CASE,
  'cabinets': AIALayer.A_CASE,
  'millwork': AIALayer.A_CASE,
  'furniture': AIALayer.A_FURN,
  'furn': AIALayer.A_FURN,
  'furnishings': AIALayer.A_FURN,
  'equipment': AIALayer.A_EQPM,
  'equip': AIALayer.A_EQPM,
  'appliance': AIALayer.A_EQPM,
  'opening': AIALayer.A_OPEN,
  'openings': AIALayer.A_OPEN,
  'shaft': AIALayer.A_SHAF,
  'shafts': AIALayer.A_SHAF,
  'chase': AIALayer.A_SHAF,
  'toilet': AIALayer.A_PLMB,
  'restroom': AIALayer.A_PLMB,
  'bathroom': AIALayer.A_PLMB,
  'plumbing_fixture': AIALayer.A_PLMB,
  'elevator': AIALayer.A_ELEV,
  'elev': AIALayer.A_ELEV,
  'escalator': AIALayer.A_ESCL,
  'duct': AIALayer.M_DUCT,
  'ducts': AIALayer.M_DUCT,
  'hvac': AIALayer.M_DUCT,
  'air_handler': AIALayer.M_DUCT,
  'diffuser': AIALayer.M_DUCT,
  'pipe': AIALayer.P_PIPE,
  'pipes': AIALayer.P_PIPE,
  'plumbing': AIALayer.P_PIPE,
  'plumb': AIALayer.P_PIPE,
  'conduit': AIALayer.E_COND,
  'conduits': AIALayer.E_COND,
  'cable_tray': AIALayer.E_CTRAY,
  'cabletray': AIALayer.E_CTRAY,
  'cable_trays': AIALayer.E_CTRAY,
  'lighting': AIALayer.E_LITE,
  'light': AIALayer.E_LITE,
  'lights': AIALayer.E_LITE,
  'luminaire': AIALayer.E_LITE,
  'fire_protection': AIALayer.F_SPRK,
  'sprinkler': AIALayer.F_SPRK,
  'fire_alarm': AIALayer.F_SPRK,
  'telecom': AIALayer.T_TELC,
  'telecommunications': AIALayer.T_TELC,
  'data': AIALayer.T_TELC,
  'network': AIALayer.T_TELC,
  'security': AIALayer.T_SEC,
  'camera': AIALayer.T_SEC,
  'access_control': AIALayer.T_SEC,
  'footing': AIALayer.S_FOOT,
  'foundation': AIALayer.S_FOOT,
  'footings': AIALayer.S_FOOT,
  'gradebeam': AIALayer.S_GRDN,
  'grade_beam': AIALayer.S_GRDN,
  'structural_column': AIALayer.S_COLN,
  'structural_columns': AIALayer.S_COLN,
  'structural_beam': AIALayer.S_BEAM,
  'structural_beams': AIALayer.S_BEAM,
  'beam': AIALayer.S_BEAM,
  'beams': AIALayer.S_BEAM,
  'brace': AIALayer.S_BRAC,
  'bracing': AIALayer.S_BRAC,
  'diagonal_brace': AIALayer.S_BRAC,
  'truss': AIALayer.S_TRUS,
  'trusses': AIALayer.S_TRUS,
  'girder': AIALayer.S_GIRD,
  'girders': AIALayer.S_GIRD,
  'joist': AIALayer.S_JOIS,
  'joists': AIALayer.S_JOIS,
  'deck': AIALayer.S_DECK,
  'decks': AIALayer.S_DECK,
  'metal_deck': AIALayer.S_DECK,
  'shearwall': AIALayer.S_SHWR,
  'shear_wall': AIALayer.S_SHWR,
  'moment_frame': AIALayer.S_MOMF,
  'momentframe': AIALayer.S_MOMF,
  'site': AIALayer.G_SITE,
  'grading': AIALayer.G_SITE,
  'topography': AIALayer.G_SITE,
  'road': AIALayer.G_ROAD,
  'roads': AIALayer.G_ROAD,
  'pavement': AIALayer.G_ROAD,
  'asphalt': AIALayer.G_ROAD,
  'sidewalk': AIALayer.G_SWAL,
  'walkway': AIALayer.G_SWAL,
  'path': AIALayer.G_SWAL,
  'curb': AIALayer.G_CURB,
  'curbs': AIALayer.G_CURB,
  'gutter': AIALayer.G_CURB,
  'fence': AIALayer.G_FENC,
  'fencing': AIALayer.G_FENC,
  'gate': AIALayer.G_FENC,
  'landscape': AIALayer.G_LNDS,
  'planting': AIALayer.G_LNDS,
  'plants': AIALayer.G_LNDS,
  'tree': AIALayer.G_LNDS,
  'parking': AIALayer.G_PARK,
  'parking_lot': AIALayer.G_PARK,
  'parking_stall': AIALayer.G_PARK,
  'retaining_wall': AIALayer.G_RETW,
  'retainingwall': AIALayer.G_RETW,
  'drainage': AIALayer.G_DRAN,
  'drain': AIALayer.G_DRAN,
  'storm_drain': AIALayer.G_DRAN,
  'existing': AIALayer.A_EXST,
  'exist': AIALayer.A_EXST,
  'exst': AIALayer.A_EXST,
  'demolish': AIALayer.A_DEMO,
  'demo': AIALayer.A_DEMO,
  'demolition': AIALayer.A_DEMO,
  'temporary': AIALayer.A_TEMP,
  'temp': AIALayer.A_TEMP,
  'future': AIALayer.A_FUTR,
  'annotation': AIALayer.A_ANNO,
  'annotations': AIALayer.A_ANNO,
  'text': AIALayer.A_ANNO,
  'label': AIALayer.A_ANNO,
  'dimension': AIALayer.A_DIMN,
  'dim': AIALayer.A_DIMN,
  'dimensions': AIALayer.A_DIMN,
  'grid': AIALayer.A_GRID,
  'grids': AIALayer.A_GRID,
  'gridline': AIALayer.A_GRID,
  'refplane': AIALayer.A_GRID,
  'bubble': AIALayer.A_CALO,
  'bubbles': AIALayer.A_CALO,
  'callout': AIALayer.A_CALO,
  'section_mark': AIALayer.A_SECM,
  'sectionmark': AIALayer.A_SECM,
  'elevation_mark': AIALayer.A_ELEM,
  'elevationmark': AIALayer.A_ELEM,
  'generic': AIALayer.GENERAL,
  'default': AIALayer.GENERAL,
  'hidden': AIALayer.HIDDEN,
  'invisible': AIALayer.HIDDEN,
  'reference': AIALayer.REFERENCE,
  'ref': AIALayer.REFERENCE,
};

export function getLayerForEntity(kind: string): AIALayer | null {
  const normalized = kind.toLowerCase().trim();
  return ENTITY_TO_LAYER[normalized] || null;
}
