mod error;
mod interval;
mod predicates;
mod roots;
mod solve;
mod union_find;
mod vector;

pub(super) use error::finite;
pub use error::MathError;
pub use interval::Interval;
pub use predicates::{discriminant, incircle2d, orient2d, orient3d, Sign};
pub(super) use predicates::{plane_sphere_relation, sphere_sphere_relation};
pub use roots::RootCandidates;
pub(super) use roots::{isolate_candidates, quadratic, QuadraticRoots};
pub(super) use solve::solve;
pub use solve::LinearSolution;
pub(super) use union_find::{find, union};
pub use vector::Point3;
pub(super) use vector::{add, cross, dot, norm, scale, sub};
